name: "GroupOrder Frontend sast-scan, check security of software"

on:
  push:
    branches:
      # - 'feature/*'
      # - 'develop'
      - 'none'

jobs:
  owasp_odc:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm ci --force
      - name: OWASP Dependency Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v9.1.0/dependency-check-9.1.0-release.zip
          unzip dependency-check-9.1.0-release.zip
      - name: Run scan with ODC
        run: |
          dependency-check/bin/dependency-check.sh --out . --scan . > ODC-report
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sast report
          path: |
            ./ODC-report
          retention-days: 1
